services:
  streamcam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamcam-app
    ports:
      - "${PORT}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage